### ISSUE TITLE
gizeh colour issue

### ISSUE THREAD

**Issue by bmer** [Zulko/gizeh#18]
Hi Zulko (and maintainers),

Excellent library -- many thanks for your work on it! 

I think I have come across an issue where in RGB colours are not being interpreted properly, I think.

Here is a minimum working example: https://gist.github.com/bmer/86b6ce9b3f67854f6214

It is small, and meant to simply reproduce the problem.

What the script does is create an image which has two coloured strips. One colour is red. The other colour is a lighter red. You can change how light you want to make the lighter red by increasing the `x` value (on `line 5`).

Now, it seems that if you make red lighter very slightly (for instance, just make it `x = 1`), the lighter red strip disappears completely!

Does this issue occur on your computers as well? 

By the way, I am using the latest version of gizeh available through pip.

**Comment by Zulko** [comment]
In Gizeh RGB colors are actually coded between 0 and 1, for instance red is (1,0,0), grey is (.5, .5, .5), etc. maybe that is your problem

**Comment by bmer** [comment]
This is right. That did end up being my problem!
