### ISSUE TITLE
Are people able to successfully install and use `cairocffi` (through `gizeh`) on Windows?

### ISSUE THREAD

**Issue by bmer** [Zulko/gizeh#19]
Hi all,

I have not been successful in installing `gizeh` on Windows, because [I am not able to get `cairocffi` to work](https://github.com/SimonSapin/cairocffi/issues/57).

Have others had the same issue, or are you able to use `gizeh` on your Windows system? 

Kind regards,
Brian

**Comment by bmer** [comment]
Apparently, I am able to install it on Windows now...okay, so never mind, and the answer is **yes**.

**Comment by timeisapear** [comment]
@bmer Hi, I am having the same issues installing--the cannot load library libcairo.so.2 error. How did you resolve it?

I am on 64-bit Windows Server 2008 with Winpython installation trying to install weasyprint (which has cairocffi/cairo as a dependency).

Thanks,
Steve

**Comment by bmer** [comment]
@timeisapear Hi, hope I am not too late to help. I downloaded the gtk all-in-one package available here: http://www.gtk.org/download/win64.php

Then, I made sure that my PATH variable (I use Rapid Environment Editor to change that around: http://www.rapidee.com/en/about) included the /bin/ directory provided by the gtk all-in-one package. 

Then, everything seemed to be relatively smooth.

**Comment by Splo0sh** [comment]
I used this 64 bit runtime installer for gtk2: http://lvserver.ugent.be/gtk-win64/gtk2-runtime/
worked fine for my 2.7.10 64bit winpython installation.
